# _config.yml
title: Hello World
description: Data Scientist | First principles thinker | Dad
author: Zak Boston
email: zak.boston@pm.me
url: zak-boston.github.io

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md     
  - about.md          
  - euler.md  

# Posts settings (your blog entries)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title.html
      author: Zak Boston
      categories: euler

show_excerpts: true  # shows preview on homepage

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1